name: "Github Events To Feishu Bot Action"
description: "send message to feishu bot"
author: "junka"
branding:
  icon: "cloud-snow"
  color: "blue"
inputs:
  webhook:
    description: "feishu bot webhook url"
    required: true
  signkey:
    description: "set when you enable signature verify"
    required: false
  github_token:
    description: "GitHub token for API access (optional, default: GITHUB_TOKEN)"
    required: false
outputs:
  code:
    description: "code from response"
runs:
  using: "node20"
  main: "dist/index.js"
